version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./temp/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: bus_tickets